<?php

/**
 * @file
 * Contains content_item_entity.page.inc.
 *
 * Page callback for Content Item entities.
 */

use Drupal\Core\Render\Element;

/**
 * Prepares variables for Content Item templates.
 *
 * Default template: content_item_entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_content_item_entity(array &$variables) {
  // Fetch ContentItemEntity Entity Object.
  $content_item_entity = $variables['elements']['#content_item_entity'];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
