<?php

use Drupal\Core\StreamWrapper\StreamWrapperManager;
use Drupal\user\Entity\Role;

/**
 * Implements hook_file_download().
 * https://www.chapterthree.com/blog/drupal-8-9-media-entities-private-files-and-broken-access-control
 */
function ubc_media_entities_file_download($uri) {
  # Check if the file is coming from the private stream wrapper
  if (StreamWrapperManager::getScheme($uri) == 'private') {

    # 1: Block anonymous users.
    if (\Drupal::currentUser()->isAnonymous()) {
      return -1;
    }

    # 2: The user does not have the permission "access private files".
    if (!\Drupal::currentUser()->hasPermission('access private files')) {
      return -1;
    }
  }

  return NULL;
}

/**
 * Implements hook_post_update_()
 * Add permission to view private files
 */
function ubc_media_entities_post_update_grant_private_file_permission() {
  $role_object = Role::load('authenticated');
  $role_object->grantPermission('access private files');
  $role_object->save();
}

/**
 * Implements hook_post_update_()
 * Update wide and narrow view modes to use lazy loading
 */
function ubc_media_entities_post_update_10001() {
  $config = \Drupal::service('config.factory');
  // alter preexisting media view mode when installing
  $config->getEditable('core.entity_view_display.media.image.full')
    ->set('content.field_media_image.settings.image_loading.attribute', 'lazy')
    ->save();
  $config->getEditable('core.entity_view_display.media.image.narrow')
    ->set('content.field_media_image.settings.image_loading.attribute', 'lazy')
    ->save();
}

/**
 * Implements hook_post_update_()
 * Add an Original Image view mode for image media
 */
function ubc_media_entities_post_update_10002() {
  $config = \Drupal::service('config.factory');
  $uuid = \Drupal::service('uuid')->generate();
  $uuid2 = \Drupal::service('uuid')->generate();
  // create new view mode
  $config_id = 'core.entity_view_mode.media.original';
  $config_path = \Drupal::service('extension.list.module')->getPath('ubc_media_entities') . '/config/install/' . $config_id .'.yml';
  $data = \Symfony\Component\Yaml\Yaml::parseFile($config_path);
  $config->getEditable($config_id)->setData($data)->save(TRUE);
  // create and add the uuid
  $config->getEditable($config_id)
    ->set('uuid', $uuid)
    ->save();
  // assign values to new view mode
  $config_id = 'core.entity_view_display.media.image.original';
  $config_path = \Drupal::service('extension.list.module')->getPath('ubc_media_entities') . '/config/install/' . $config_id .'.yml';
  $data = \Symfony\Component\Yaml\Yaml::parseFile($config_path);
  $config->getEditable($config_id)->setData($data)->save(TRUE);
  // create and add the uuid
  $config->getEditable($config_id)
    ->set('uuid', $uuid2)
    ->save();
}
