name: UBC Editor Configuration - Simple Format
type: module
description: This module defines a simple configuration for Drupal's WYSIWYG, cKeditor.
package: UBC Web Services
dependencies:
  - drupal:ckeditor
  - drupal:linkit
core_version_requirement: ^9 || ^10
