<?php

/**
 * @file
 * Contains ubc_share_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ubc_share_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ubc_share_block module.
    case 'help.page.ubc_share_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module adds a block of share links for various social media platforms.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ubc_share_block_theme($existing, $type, $theme, $path) {
  return [
    'ubc_share_block' => [
      'variables' => [
        'twitter' => NULL,
        'pinterest' => NULL,
        'facebook' => NULL,
        'linkedin' => NULL,
        'reddit' => NULL,
        'email' => NULL,
        'share_site_url' => NULL,
      ],
    ],
  ];
}
