<?php

/**
 * @file
 * Contains ubc_prargraph_entities.module.
 */

/**
 * Implements hook_theme().
 */
function ubc_paragraph_entities_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__card_group' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__card_horizontal' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__card_vertical' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__feature_image' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__icon_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__image_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__slide' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__slideshow' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__tabcordion' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__text' => [
      'base hook' => 'paragraph',
    ],
  ];
}
