<?php
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Entity\EntityInterface;

/*
 * Implements hook_ENTITY_TYPE_access().
 */

function ubc_private_page_node_access(EntityInterface $entity, $operation, AccountInterface $account) {
    // Checks for private node type when viewing node.
    $type = $entity->bundle();
    if ($operation === 'view') {
        if ($account
        ->hasPermission('view private pages') && $type === 'private_page') {
            return AccessResult::allowed();
        }
        else {
            return AccessResult::forbidden();
        }
    }
    return AccessResult::neutral();
}
